import { SDNode } from "@/Node/SDNode";
import { Color } from "@/Utility/Color";

type InputID = number | string;
type InputNode = InputNode;

export class BaseTree extends SDNode {
    constructor(parent: SDNode);

    newNode(id: InputID): this;
    newNode(id: InputID, value: any): this;
    newNodeFromExistValue(id: InputID, value: SDNode): this;
    newNodeFromExistElement(id: InputID, element: SDNode): this;
    newLink(sourceId: InputID, targetId: InputID): this;
    newLink(sourceId: InputID, targetId: InputID, value: any): this;
    newLinkFromExistValue(sourceId: InputID, targetId: InputID, value: SDNode): this;
    newLinkFromExistElement(sourceId: InputID, targetId: InputID, element: SDNode): this;
    element(node: InputNode): SDNode;
    element(source: InputNode, target: InputNode): SDNode;
    value(node: InputNode): SDNode;
    value(node: InputNode, value: any): this;
    value(source: InputNode, target: InputNode): SDNode;
    value(source: InputNode, target: InputNode, value: any): this;
    opacity(): number;
    opacity(opacity: number): this;
    opacity(id: InputID): number;
    opacity(id: InputID, opacity: number): this;
    opacity(sourceId: InputID, targetId: InputID): number;
    opacity(sourceId: InputID, targetId: InputID, opacity: number): this;
    color(color: Color): this;
    color(tid: InputID): Color;
    color(tid: InputID, color: Color): this;
    color(sourceId: InputID, targetId: InputID): Color;
    color(sourceId: InputID, targetId: InputID, color: Color): this;
    findNode(condition: (node: SDNode, id: string) => boolean): SDNode | undefined;
    findNodes(condition: (node: SDNode, id: string) => boolean): Array<SDNode>;
    findLink(condition: (link: SDNode, sourceId: string, targetId: string) => boolean): SDNode | undefined;
    findLinks(condition: (link: SDNode, sourceId: string, targetId: string) => boolean): Array<SDNode>;
    findNodeById(tid: InputID): SDNode | undefined;
    findLinkById(sourceId: InputID, targetId: InputID): SDNode | undefined;
    inLink(node: InputNode): SDNode | undefined;
    outLinks(node: InputNode): Array<SDNode>;
    stratify();
    father(node: InputNode): SDNode | undefined;
    fatherId(node: InputNode): string;
    ancestor(node: InputNode, kth: number): SDNode | undefined;
    ancestorId(node: InputNode, kth: number): string;
    depth(): number;
    depth(node: InputNode): number;
    lca(x: InputNode, y: InputNode): SDNode;
    lcaId(x: InputNode, y: InputNode): string;
    children(id: InputNode): Array<SDNode>;
    root(): SDNode;
    root(id: InputID): this;
    root(id: InputID, value: any): this;
    link(sourceId: InputID, targetId: InputID): this;
    link(sourceId: InputID, targetId: InputID, value: any): this;
    cut(sourceId: InputID, targetId: InputID): this;
    text(tid: InputID): string;
    text(sourceId: InputID, targetId: InputID): string;
    intValue(tid: InputID): number;
    intValue(sourceId: InputID, targetId: InputID): number;
    nodesOnPath(source: InputNode, target: InputNode): Array<SDNode>;
    linksOnPath(source: InputNode, target: InputNode): Array<SDNode>;
    forEachNodeOnPath(sourceId: InputID, targetId: InputID, callback: (node: SDNode, id: string) => void): this;
    forEachLinkOnPath(sourceId: InputID, targetId: InputID, callback: (link: SDNode, sourceId: string, targetId: string) => void): this;
    forEachNode(callback: (node: SDNode, tid: string) => void): this;
    forEachLink(callback: (link: SDNode, sourceId: string, targetId: string) => void): this;
    rootId(): string;
    nodeId(node: InputNode): string | undefined;
    sourceId(link: SDNode): string | undefined;
    targetId(link: SDNode): string | undefined;
    source(link: SDNode): SDNode | undefined;
    target(link: SDNode): SDNode | undefined;
}
